import { categories } from './categories.mocks';
import { ingredients } from './ingredients.mocks';
import { allergens } from './allergens.mocks';
import { DishDto } from '../dto';


export const dishes: DishDto[] = [
  {
    _id: '1',
    fullName: 'Salade Caesar',
    shortName: 'Caesar',
    description:
      'Retrouvez notre salade Caesar : Laitue romaine, poulet grillé, croûtons, parmesan, sauce Caesar',
    price: 12,
    category: categories[0],
    ingredients: [
      ingredients[1],
      ingredients[3],
      ingredients[13],
      ingredients[14],
      ingredients[12],
    ],
    allergens: [allergens[0], allergens[2]],
    image: 'https://example.com/caesar_salad.jpg',
  },
  {
    _id: '2',
    fullName: 'Spaghetti Bolognese',
    shortName: 'Bolognese',
    description:
      'Pâtes spaghetti servies avec une sauce bolognaise riche en viande, tomates, oignons et herbes.',
    price: 14,
    category: categories[1],
    ingredients: [ingredients[0], ingredients[2], ingredients[46]],
    allergens: [allergens[1], allergens[3]],
    image: 'https://example.com/spaghetti_bolognese.jpg',
  },
  {
    _id: '3',
    fullName: 'Tiramisu',
    shortName: 'Tiramisu',
    description:
      'Un dessert italien classique à base de mascarpone, café et cacao.',
    price: 6,
    category: categories[2],
    ingredients: [ingredients[20], ingredients[22], ingredients[26]],
    allergens: [allergens[0], allergens[1]],
    image: 'https://example.com/tiramisu.jpg',
  },
  {
    _id: '4',
    fullName: 'Limonade Maison',
    shortName: 'Limonade',
    description:
      "Limonade fraîchement préparée avec des citrons, de l'eau pétillante et une touche de sucre.",
    price: 3,
    category: categories[2],
    ingredients: [ingredients[26], ingredients[24], ingredients[25]],
    allergens: [allergens[0]],
    image: 'https://example.com/limonade.jpg',
  },
  {
    _id: '5',
    fullName: 'Wrap Végétarien',
    shortName: 'Wrap Végétarien',
    description:
      'Un wrap frais et savoureux rempli de légumes croquants, de houmous et de feta.',
    price: 9,
    category: categories[0],
    ingredients: [
      ingredients[0],
      ingredients[1],
      ingredients[5],
      ingredients[6],
      ingredients[7],
      ingredients[12],
    ],
    allergens: [allergens[0], allergens[1]],
    image: 'https://example.com/wrap_vegetarien.jpg',
  },
  {
    _id: '6',
    fullName: 'Jus de Pomme Frais',
    shortName: 'Jus de Pomme',
    description:
      'Jus de pomme fraîchement pressé, sucré naturellement et rafraîchissant.',
    price: 3,
    category: categories[2],
    ingredients: [ingredients[27], ingredients[48]],
    allergens: [],
    image: 'https://example.com/jus_de_pomme.jpg',
  },
  {
    _id: '7',
    fullName: 'Café Expresso',
    shortName: 'Café',
    description:
      'Un café expresso riche et aromatique, préparé avec des grains de café de haute qualité.',
    price: 2,
    category: categories[2],
    ingredients: [ingredients[29]],
    allergens: [],
    image: 'https://example.com/cafe_expresso.jpg',
  },
  {
    _id: '8',
    fullName: "Serv'Burger",
    shortName: 'Burger',
    description: 'Un burger juteux servi avec des frites croustillantes.',
    price: 11,
    category: categories[0],
    ingredients: [
      ingredients[0],
      ingredients[1],
      ingredients[2],
      ingredients[3],
      ingredients[4],
      ingredients[5],
      ingredients[6],
      ingredients[46],
    ],
    allergens: [allergens[0], allergens[1]],
    image: 'https://example.com/serv_burger.jpg',
  },
  {
    _id: '9',
    fullName: 'Pates Carbonara',
    shortName: 'Carbonara',
    description: 'Des pâtes crémeuses avec du bacon, des œufs et du fromage.',
    price: 12,
    category: categories[1],
    ingredients: [
      ingredients[4],
      ingredients[15],
      ingredients[6],
      ingredients[45],
    ],
    allergens: [],
    image: 'https://example.com/pates_carbonara.jpg',
  },
  {
    _id: '10',
    fullName: 'Mousse au Chocolat',
    shortName: 'Mousse Chocolat',
    description: 'Une mousse légère et aérienne au chocolat noir riche.',
    price: 5,
    category: categories[2],
    ingredients: [ingredients[20], ingredients[45], ingredients[26]],
    allergens: [],
    image: 'https://example.com/mousse_au_chocolat.jpg',
  },
  {
    _id: '11',
    fullName: 'Saumon fumé',
    shortName: 'Saumon fumé',
    description:
      'Tranches de saumon fumé servies avec du pain grillé et du citron.',
    price: 13,
    category: categories[0],
    ingredients: [ingredients[47], ingredients[18], ingredients[25]],
    allergens: [allergens[4]],
    image: 'https://example.com/saumon_fume.jpg',
  },
  {
    _id: '12',
    fullName: 'Guacamole et Chips',
    shortName: 'Guacamole',
    description:
      'Un guacamole crémeux servi avec des chips de tortilla croustillantes.',
    price: 8,
    category: categories[0],
    ingredients: [ingredients[5], ingredients[6], ingredients[0]],
    allergens: [],
    image: 'https://example.com/guacamole_et_chips.jpg',
  },
];
