import { IngredientDto } from "../dto";


export const ingredients: IngredientDto[] = [

    { _id: '1', name: 'Tomate', extraCost: 0.5},
    { _id: '2', name: 'Salade', extraCost: 0.3},
    { _id: '3', name: 'Fromage', extraCost: 1.0},
    { _id: '4', name: 'Poulet', extraCost: 2.0},
    { _id: '5', name: 'Bacon', extraCost: 1.5},
    { _id: '6', name: 'Avocat', extraCost: 1.2},
    { _id: '7', name: 'Oignons', extraCost: 0.4},
    { _id: '8', name: 'Champignons', extraCost: 0.8},
    { _id: '9', name: 'Poivre', extraCost: 0.6},
    { _id: '10', name: 'Epinard', extraCost: 0.7},
    { _id: '11', name: 'Olives', extraCost: 0.9},
    { _id: '12', name: 'Feta', extraCost: 1.3},
    { _id: '13', name: 'Croutons', extraCost: 0.5},
    { _id: '14', name: 'Parmesan', extraCost: 1.4},
    { _id: '15', name: 'Sauce Caesar', extraCost: 0.6},
    { _id: '16', name: 'Pates', extraCost: 1.0},
    { _id: '17', name: 'Sauce Tomate', extraCost: 0.7},
    { _id: '18', name: 'Viande', extraCost: 2.5},
    { _id: '19', name: 'Pain à l\'ail', extraCost: 1.2},
    { _id: '20', name: 'Basilic', extraCost: 0.4},
    { _id: '21', name: 'Chocolat', extraCost: 1.5},
    { _id: '22', name: 'Fraises', extraCost: 1.0},
    { _id: '23', name: 'Crème Anglaise', extraCost: 0.8},
    { _id: '24', name: 'Glace Vanille', extraCost: 1.2},
    { _id: '25', name: 'Menthe', extraCost: 0.3},
    { _id: '26', name: 'Citron', extraCost: 0.4},
    { _id: '27', name: 'Sucre', extraCost: 0.2},
    { _id: '28', name: 'Eau', extraCost: 0.0},
    { _id: '29', name: 'Soda', extraCost: 0.5},
    { _id: '30', name: 'Cafe', extraCost: 1.0},
    { _id: '31', name: 'The', extraCost: 0.8},
    { _id: '32', name: 'Lait', extraCost: 0.6},
    { _id: '33', name: 'Citron vert', extraCost: 0.4},
    { _id: '34', name: 'Concombres', extraCost: 0.5},
    { _id: '35', name: 'Carottes', extraCost: 0.3},
    { _id: '36', name: 'Céleri', extraCost: 0.4},
    { _id: '37', name: 'Houmous', extraCost: 1.0},
    { _id: '38', name: 'Pain pita', extraCost: 0.7},
    { _id: '39', name: 'Falafel', extraCost: 1.5},
    { _id: '40', name: 'Sauce Tahini', extraCost: 0.6},
    { _id: '41', name: 'Aubergines', extraCost: 0.8},
    { _id: '42', name: 'Courgettes', extraCost: 0.7},
    { _id: '43', name: 'Pois chiches', extraCost: 1.0},
    { _id: '44', name: 'Coriandre', extraCost: 0.3},
    { _id: '45', name: 'Grains de café', extraCost: 0.7},
    { _id: '46', name: 'Oeufs', extraCost: 1.5},
    { _id: '47', name: 'Steak', extraCost: 2.5},
    { _id: '48', name: 'Saumon', extraCost: 3.0},
    { _id: '49', name: 'Pommes', extraCost: 2.0},

]
