import { IngredientDto } from "../dto";


export const ingredients: IngredientDto[] = [

    { _id: '1', name: 'Tomato', extraCost: 0.5, quantity: "base" },
    { _id: '2', name: 'Lettuce', extraCost: 0.3, quantity: "base" },
    { _id: '3', name: 'Cheese', extraCost: 1.0, quantity: "base" },
    { _id: '4', name: 'Chicken', extraCost: 2.0, quantity: "base" },
    { _id: '5', name: 'Bacon', extraCost: 1.5, quantity: "base" },
    { _id: '6', name: 'Avocado', extraCost: 1.2, quantity: "base" },
    { _id: '7', name: 'Onion', extraCost: 0.4, quantity: "base" },
    { _id: '8', name: 'Mushroom', extraCost: 0.8, quantity: "base" },
    { _id: '9', name: 'Bell Pepper', extraCost: 0.6, quantity: "base" },
    { _id: '10', name: 'Spinach', extraCost: 0.7, quantity: "base" },
    { _id: '11', name: 'Olives', extraCost: 0.9, quantity: "base" },
    { _id: '12', name: 'Feta Cheese', extraCost: 1.3, quantity: "base" },
    { _id: '13', name: 'Croutons', extraCost: 0.5, quantity: "base" },
    { _id: '14', name: 'Parmesan', extraCost: 1.4, quantity: "base" },
    { _id: '15', name: 'Caesar Dressing', extraCost: 0.6, quantity: "base" },
    { _id: '16', name: 'Pasta', extraCost: 1.0, quantity: "base" },
    { _id: '17', name: 'Tomato Sauce', extraCost: 0.7, quantity: "base" },
    { _id: '18', name: 'Meatballs', extraCost: 2.5, quantity: "base" },
    { _id: '19', name: 'Garlic Bread', extraCost: 1.2, quantity: "base" },
    { _id: '20', name: 'Basil', extraCost: 0.4, quantity: "base" },
    { _id: '21', name: 'Chocolate', extraCost: 1.5, quantity: "base" },
    { _id: '22', name: 'Strawberries', extraCost: 1.0, quantity: "base" },
    { _id: '23', name: 'Whipped Cream', extraCost: 0.8, quantity: "base" },
    { _id: '24', name: 'Vanilla Ice Cream', extraCost: 1.2, quantity: "base" },
    { _id: '25', name: 'Mint', extraCost: 0.3, quantity: "base" },
    { _id: '26', name: 'Lemon', extraCost: 0.4, quantity: "base" },
    { _id: '27', name: 'Sugar', extraCost: 0.2, quantity: "base" },
    { _id: '28', name: 'Water', extraCost: 0.0, quantity: "base" },
    { _id: '29', name: 'Soda', extraCost: 0.5, quantity: "base" },
    { _id: '30', name: 'Coffee', extraCost: 1.0, quantity: "base" },
    { _id: '31', name: 'Tea', extraCost: 0.8, quantity: "base" },
    { _id: '32', name: 'Milk', extraCost: 0.6, quantity: "base" },
    { _id: '33', name: 'Lime', extraCost: 0.4, quantity: "base" },
    { _id: '34', name: 'Cucumber', extraCost: 0.5, quantity: "base" },
    { _id: '35', name: 'Carrot', extraCost: 0.3, quantity: "base" },
    { _id: '36', name: 'Celery', extraCost: 0.4, quantity: "base" },
    { _id: '37', name: 'Hummus', extraCost: 1.0, quantity: "base" },
    { _id: '38', name: 'Pita Bread', extraCost: 0.7, quantity: "base" },
    { _id: '39', name: 'Falafel', extraCost: 1.5, quantity: "base" },
    { _id: '40', name: 'Tahini Sauce', extraCost: 0.6, quantity: "base" },
    { _id: '41', name: 'Eggplant', extraCost: 0.8, quantity: "base" },
    { _id: '42', name: 'Zucchini', extraCost: 0.7, quantity: "base" },
    { _id: '43', name: 'Chickpeas', extraCost: 1.0, quantity: "base" },
    { _id: '44', name: 'Cilantro', extraCost: 0.3, quantity: "base" },
    { _id: '45', name: 'Coffee Beans', extraCost: 0.7, quantity: "base" },
    { _id: '46', name: 'Egg', extraCost: 1.5, quantity: "base" },
    { _id: '47', name: 'Steak', extraCost: 2.5, quantity: "base" },
    { _id: '48', name: 'Salmon', extraCost: 3.0, quantity: "base" },
    { _id: '49', name: 'Apple', extraCost: 2.0, quantity: "base" },

]
